typography_spectrum: 0.967314210254699
color:
  brandStrength: 0.5254728470463306
  lightness: 0.4346636263653636
  saturation: 0.09799328609369695
  rhythmicContrast: 0.914325597230345
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.35984181915409863
author:
  name: Ã–rjan
name: emotional machine productions
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/db97280e-9335-4edc-b18a-7be9e127d17e.jpg
